# Generated by Django 3.0.5 on 2020-05-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCourser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_courser', models.IntegerField()),
                ('content', models.CharField(max_length=2000)),
                ('nameContent', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Courser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCourser', models.CharField(max_length=200)),
                ('starCourser', models.CharField(max_length=50)),
                ('imageCourser', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LearningOutcomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('id_courser', models.IntegerField()),
                ('output', models.CharField(max_length=200)),
            ],
        ),
    ]
